
version: 2
general:
  branches:
    only:
      - main
jobs:
  build:
    docker:
     - image: circleci/mongo:latest
    triggers:
      - schedule:
          cron: "0 0 * * *"
    steps: 
      - run: # Install AWS cli
           name: Install AWS cli
           command: |
              apt-get update
              apt-get -y install curl
              apt-get -y install unzip
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              ./aws/install
              aws --version
      - run:
            name: Create lab dump
            command: |
                mongodump --uri mongodb+srv://solena:zkYr651NSXH92bOm@cluster0.euggj.gcp.mongodb.net/smart_soil_lab
      - run:
            name: Create sampler dump
            command: |
                mongodump --uri mongodb+srv://solena:ogAH1RK9dvQhA6IE@cluster0.od7ve.mongodb.net/smart-dev
      - run: # Deploy to S3 using the sync command
                name: Deploy to S3
                command: aws s3 sync dump s3://db-backups-solena/"`date +"%d-%m-%Y"`"