
version: 2
general:
  branches:
    only:
      - main
jobs:
  build:
    docker:
     - image: circleci/mongo:latest

    steps: 
      - run: # Test mongo
          sudo apt install curl
        
      
            
            
    
          
