
version: 2
general:
  branches:
    only:
      - main
jobs:
  build:
    docker:
      - image: cimg/python:3.9.2

    steps: 
      - run: # Test mongo
          name: Test
          command: |
            sudo apt install mongodb-org-tools
    
          
