
version: 2
general:
  branches:
    only:
      - main
jobs:
  build:
    docker:
     - image: circleci/mongo:latest

    steps: 
      - run: # Test mongo
          apt-get curl 
          apt-get unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          aws --version
      
            
            
    
          
