
version: 2
general:
  branches:
    only:
      - main
jobs:
  build:
    docker:
      - image: cimg/python:3.9.2
      - image: circleci/mongo:latest

    steps:
      - run: # Test mongo
          name: Test
          command: |
            cd .. 
      - run: # Test mongo
          name: Test
          command: |
            ls
            
          
