
version: 2
general:
  branches:
    only:
      - main
jobs:
  build:
    docker:
      - image: cimg/go:1.15.10

    steps: 
      - run: # Test mongo
          name: Test
          command: |
            git clone https://github.com/mongodb/mongo-tools
            cd mongo-tools
            go run build.go build
            ls
            
            
    
          
