
version: 2
general:
  branches:
    only:
      - main
jobs:
  build:
    docker:
      - image: circleci/mongo:latest

    steps: 
      - run: # Test mongo
          name: Test
          command: |
            mongodump --uri mongodb+srv://solena:zkYr651NSXH92bOm@cluster0.euggj.gcp.mongodb.net/smart_soil_lab
            ls
            
            
    
          
