
version: 2
general:
  branches:
    only:
      - main
jobs:
  build:
    docker:
     - image: circleci/mongo:latest

    steps: 
      - run: # Deploy to S3 using the sync command
           name: Test
           command: |
              apt-get update
              apt-get -y install curl



       
        
      
            
            
    
          
