
version: 2
general:
  branches:
    only:
      - main
jobs:
  build:
    docker:
      - image: cimg/python:3.9.2

    steps:
      - checkout
      - run: # Install the AWS CLI if it is not already included in the docker image
          name: Install awscli 
          command: |
            pip3 install awscli
            
          
