
version: 2
general:
  branches:
    only:
      - main
jobs:
  build:
    docker:
      - image: cimg/python:3.9.2
      - image: circleci/mongo:4.2.0

    steps:
      - run: # Test mongo
          name: Test
          command: |
            mongo --version
    
          
