
version: 2
general:
  branches:
    only:
      - main
jobs:
  build:
    docker:
     - image: circleci/mongo:latest

    steps: 
      - run: # Deploy to S3 using the sync command
           name: Test
           command: |
              apt-get update
              apt-get -y install curl
              apt-get -y install unzip
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              ./aws/install
              aws --version



       
        
      
            
            
    
          
