
version: 2
general:
  branches:
    only:
      - main
jobs:
  build:
    docker:
      - image: cimg/python:3.9.2

    steps: 
      - run: # Test mongo
          name: Test
          command: |
            git clone https://github.com/mongodb/mongo-tools
            cd mongo-tools
            ./make build
            ls
            
    
          
